#! /usr/bin/env sh

echo "[info] Updating submodule..."
ROOTDIR=$(git rev-parse --show-toplevel)
pushd $ROOTDIR
git submodule update
popd
echo "[info] Cleaning brainflight..."
./clean
echo "[info] Building play..."
cp -rf playframework/preCompiledFiles/* playframework/
cd playframework/framework
./build publish-local

