// Generated by CoffeeScript 1.4.0
(function() {

  define(["graph"], function(Graph) {
    var Controller;
    return Controller = (function() {
      var HEIGHT, WIDTH;

      WIDTH = 960;

      HEIGHT = 500;

      function Controller() {
        var _this = this;
        this.svg = d3.select("body").append("svg").attr("WIDTH", WIDTH).attr("HEIGHT", HEIGHT).attr("pointer-events", "all");
        this.svg.append('svg:g');
        this.svg.append('svg:rect').attr('width', WIDTH).attr('height', HEIGHT).attr('fill', 'white').call(d3.behavior.zoom().on("zoom", (function() {
          return _this.redraw();
        })));
        this.zoom = this.svg.append('svg:g');
        this.graph = new Graph(this.zoom, WIDTH, HEIGHT);
      }

      Controller.prototype.redraw = function() {
        return this.zoom.attr("transform", "translate(" + d3.event.translate + ") scale(" + d3.event.scale + ")");
      };

      return Controller;

    })();
  });

}).call(this);
